version: '3'

services:
  login:
    build: ./login
    ports:
      - "8081:8080"
    environment:
      - NODE_ENV=development
    volumes:
      - login-data:/app/prisma

  new-product:
    build: ./new-product
    ports:
      - "8082:8080"
    environment:
      - NODE_ENV=development

volumes:
  login-data:
