services:
  login:
    image: login-service
    build:
      context: ./login
    ports:
      - "5001:80"  # Mapeia a porta 5001 do host para a 80 do contêiner
    network_mode: host

  otimizar:
    image: otimizar-service
    build:
      context: ./otimizar
    ports:
      - "5002:80"
    network_mode: host

  notificacao:
    image: notificacao-service
    build:
      context: ./notificacao
    ports:
      - "5003:80"
    network_mode: host
